### ISSUE TITLE
GETA Vise Sity hak halp !!!

### ISSUE THREAD

**Issue by MarkDroid** [JavkhlanK/Sketchware-Pro#15]
elo bor somwan til me dis cod hak GETA Vise Sity ? 

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_1_8
    targetCompatibility JavaVersion.VERSION_1_8
  }

bor pls tilmi if dis rili hak GETA Vise Sity 🙏🙏😔
😎😀👍👍

**Comment by JavkhlanK** [comment]
dude go to bed

**Comment by MarkDroid** [comment]
themnk bor cod wokr !! 😎🙏

**Comment by JavkhlanK** [comment]
ok

**Comment by MarkDroid** [comment]
bor !

**Comment by JavkhlanK** [comment]
go to bed
