### ISSUE TITLE
Lagy

### ISSUE THREAD

**Issue by Sketchdost** [JavkhlanK/Sketchware-Pro#68]
Sketchware studio 6.4.2 is to much lagy in Android 11

**Comment by ToastcodeDev** [comment]
You are right, due to the new modules that were implemented, it became more robust and therefore tends to require more resources than normal.

**Comment by ToastcodeDev** [comment]
> Sketchware studio 6.4.2 is to much lagy in Android 11

Although if you mean the **Studio** edition, no idea, this is the **Pro** version.

**Comment by AlucardTN** [comment]
as ToastCodeDev said, it's sketchware pro here, not Studio, so it's beyond our scopes

**Comment by ToastcodeDev** [comment]
> as ToastCodeDev said, it's sketchware pro here, not Studio, so it's beyond our scopes

You are right about the performance, although I do not know about the application itself, Sketchware Pro has lag

**Comment by AlucardTN** [comment]
the lag is because many custom components and blocks.

**Comment by JavkhlanK** [comment]
We're working on a quicker build time of projects, stay tuned! I'm not sure about the general performance of Sketchware Pro though, AFAIK we haven't changed anything drastic to all activities.

**Comment by ToastcodeDev** [comment]
> We're working on a quicker build time of projects, stay tuned! I'm not sure about the general performance of Sketchware Pro though, AFAIK we haven't changed anything drastic to all activities.

It's fine, although just in case the performance drops when displaying the list of projects on the device.
